replicaCount: 1

image:
  repository: registry.digitalocean.com/gigabot/gigabot-srv
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
- name: gigabot
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

env:
  COINMARKETCAP_URL: "https://pro-api.coinmarketcap.com"
  DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1232504195442020382/lumCFx7zfkHg5RejgndwMGz6x6TLRVH-ye5-WdkL3T378fRw8dSTiR74bY9OPNyjrCxz"

# Specify the secret name here, which should already be created in your cluster
secret:
  name: "gigabot-secret"
